### ISSUE TITLE
support for nested anonymous structs

### ISSUE THREAD

**Issue by exellian** [oooutlk/structx#2]
System: macos
rust: 1.71 nightly
inwelling: 0.5
structx: 0.1.8

I tried to compile the following program:
```rust
use structx::*;

pub type Props<T, T1> = Structx!{
    items: Vec<T>,
    products: Vec<Structx!{ name: T1 }>
};

fn main() {}
```

I used the following build.rs:
```rust 
fn main() {
    inwelling::to( "structx" );
}
```
and a following cargo.toml:
```toml
...
[dependencies]
structx = { version="0.1", features=[] }

[build-dependencies]
inwelling = "0.5"

[package.metadata.inwelling]
structx = true
```
Currently the compiler throws a: cannot find type `structx_items_products` in this scope, error.
Is this a general problem that nested anonymous structs are not currently supported or that generics are not supported?
