### ISSUE TITLE
Cannot find struct, variant or union type `structx_...` in this scope

### ISSUE THREAD

**Issue by jacobgmathew** [oooutlk/structx#9]
I'm not able to get a minimal example woking:

### main.rs
```
use structx::*;
pub fn main() {
    let foo = structx! { foo: "foo" };
}
```
### Cargo.toml
```
[package]
name = "test-structx"
version = "0.1.0"
edition = "2021"

[dependencies]
structx = "0.1.11"
```

I get the following error:
```
cannot find struct, variant or union type `structx_foo` in this scope
```

I'm on: 

```
os: MacOS 14.1.2
rustc: 1.75.0 
```

**Comment by oooutlk** [comment]
Change your Cargo.toml as follows:

```toml 
[package] 
name = "test-structx"
version = "0.1.0"
edition = "2021"

[dependencies]
structx = "0.1.11"

[build-dependencies]
inwelling = "0.5"

[package.metadata.inwelling]
structx = true
```

And add `build.rs` as follows:

```rust
fn main() { 
    inwelling::to("structx");
}
```

See [`structx_test`](https://github.com/oooutlk/structx/tree/main/structx_test) for more.
